/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, MeshWobbleMaterial, Edges, Environment } from "@react-three/drei";


export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modernport/Llama.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={4.58}>
      <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
        >
            <meshStandardMaterial color="#A865C9" roughness={0.1} metalness={0.15}/>
            <Edges
                scale={1.5}
                threshold={3} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
                color="white"
                position={[0,-0.8,0]}
            />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
        >
            <MeshWobbleMaterial factor={0.4} speed={3} color="#A865C9" roughness={0.1} metalness={0.15}/>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          >
          <MeshWobbleMaterial factor={0.2} speed={3} color="#000" roughness={0.1} metalness={0.15}/>
      </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          >

          <meshStandardMaterial color="#000" roughness={0.1} metalness={0.15}/>
      </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials["Material.003"]}
        >
            <Edges
                scale={1.5}
                threshold={50} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
                color="white"
                position={[0,-0.8,0]}
            />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials.Material}
        >
            <Edges
                scale={1.5}
                threshold={3} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
                color="purple"
                position={[0,-0.8,0]}
            />
        </mesh>
      </group>
      <Environment preset="warehouse"/>
    </group>
  );
}

useGLTF.preload("/modernport/Llama.glb");

